# Generated by Django 3.2.8 on 2022-06-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210814_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='full_desription',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
