# Generated by Django 3.2.8 on 2022-06-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skills_about_skills_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='desription',
            field=models.TextField(max_length=300),
        ),
    ]
